apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: reverse-words
spec:
  host: pro-reverse-words-reverse-words.apps.cluster-e675.sandbox1489.opentlc.com
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: reverse-words
    weight: 50
