{
 "title": "CR Dashboard Http Request",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Alert Http Request Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ALERTS{alertname=\"HttpRequestRateAlert\"}"
    }
   ]
  },
  {
   "title": "Alert Http Request Total",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ALERTS{alertname=\"HttpRequestAlert\"}"
    }
   ]
  },
  {
   "title": "Total http request",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_requests_total{job=\"prometheus-example-app\"}"
    }
   ]
  },
  {
   "title": "Rate  http requests (1min)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_requests_total{job=\"prometheus-example-app\"}[1m])"
    }
   ]
  }
 ]
}